CREATE (F:Categoria {nombre: "Fotografía"})
CREATE (D:Categoria {nombre: "Diseño Gráfico"})
CREATE (E:Categoria {nombre: "Escritura Creativa"})
CREATE (M:Categoria {nombre: "Música"})


CREATE (F1:Curso {titulo: "fotos1"})
CREATE (F2:Curso {titulo: "fotos2"})
CREATE (F3:Curso {titulo: "fotos3"})
CREATE (F1)-[:PERTENECE_A]->(F)
CREATE (F2)-[:PERTENECE_A]->(F)
CREATE (F3)-[:PERTENECE_A]->(F)

CREATE (D1:Curso {titulo: "diseño1"})
CREATE (D2:Curso {titulo: "diseño2"})
CREATE (D3:Curso {titulo: "diseño3"})
CREATE (D1)-[:PERTENECE_A]->(D)
CREATE (D2)-[:PERTENECE_A]->(D)
CREATE (D3)-[:PERTENECE_A]->(D)

CREATE (E1:Curso {titulo: "escritura1"})
CREATE (E2:Curso {titulo: "escritura2"})
CREATE (E3:Curso {titulo: "escritura3"})
CREATE (E1)-[:PERTENECE_A]->(E)
CREATE (E2)-[:PERTENECE_A]->(E)
CREATE (E3)-[:PERTENECE_A]->(E)

CREATE (M1:Curso {titulo: "musica1"})
CREATE (M2:Curso {titulo: "musica2"})
CREATE (M3:Curso {titulo: "musica3"})
CREATE (M1)-[:PERTENECE_A]->(M)
CREATE (M2)-[:PERTENECE_A]->(M)
CREATE (M3)-[:PERTENECE_A]->(M)